# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 500)
        MainWindow.setMinimumSize(QtCore.QSize(300, 500))
        MainWindow.setMaximumSize(QtCore.QSize(300, 500))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PowerButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PowerButton.setGeometry(QtCore.QRect(210, 10, 71, 21))
        self.PowerButton.setObjectName("PowerButton")
        self.VolumeUpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.VolumeUpButton.setGeometry(QtCore.QRect(40, 260, 81, 31))
        self.VolumeUpButton.setObjectName("VolumeUpButton")
        self.ChannelUpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ChannelUpButton.setGeometry(QtCore.QRect(170, 260, 91, 32))
        self.ChannelUpButton.setObjectName("ChannelUpButton")
        self.VolumeDownButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.VolumeDownButton.setGeometry(QtCore.QRect(40, 310, 81, 32))
        self.VolumeDownButton.setObjectName("VolumeDownButton")
        self.ChannelDownButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ChannelDownButton.setGeometry(QtCore.QRect(170, 310, 91, 32))
        self.ChannelDownButton.setObjectName("ChannelDownButton")
        self.MuteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.MuteButton.setGeometry(QtCore.QRect(110, 350, 71, 51))
        self.MuteButton.setObjectName("MuteButton")
        self.StatusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.StatusLabel.setGeometry(QtCore.QRect(60, 80, 171, 20))
        self.StatusLabel.setText("")
        self.StatusLabel.setObjectName("StatusLabel")
        self.ChannelDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.ChannelDisplay.setGeometry(QtCore.QRect(50, 50, 201, 141))
        self.ChannelDisplay.setText("")
        self.ChannelDisplay.setObjectName("ChannelDisplay")
        self.labelzero = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelzero.setGeometry(QtCore.QRect(70, 200, 16, 16))
        self.labelzero.setObjectName("labelzero")
        self.labelone = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelone.setGeometry(QtCore.QRect(100, 200, 21, 16))
        self.labelone.setObjectName("labelone")
        self.labeltwo = QtWidgets.QLabel(parent=self.centralwidget)
        self.labeltwo.setGeometry(QtCore.QRect(130, 200, 16, 16))
        self.labeltwo.setObjectName("labeltwo")
        self.labelthree = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelthree.setGeometry(QtCore.QRect(160, 200, 21, 16))
        self.labelthree.setObjectName("labelthree")
        self.labelfour = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelfour.setGeometry(QtCore.QRect(190, 200, 21, 16))
        self.labelfour.setObjectName("labelfour")
        self.labelfive = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelfive.setGeometry(QtCore.QRect(220, 200, 60, 16))
        self.labelfive.setObjectName("labelfive")
        self.VolumeBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.VolumeBar.setGeometry(QtCore.QRect(70, 220, 161, 23))
        self.VolumeBar.setProperty("value", 24)
        self.VolumeBar.setObjectName("VolumeBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PowerButton.setText(_translate("MainWindow", "ON/OFF"))
        self.VolumeUpButton.setText(_translate("MainWindow", "Volume +"))
        self.ChannelUpButton.setText(_translate("MainWindow", "Channel +"))
        self.VolumeDownButton.setText(_translate("MainWindow", "Volume -"))
        self.ChannelDownButton.setText(_translate("MainWindow", "Channel - "))
        self.MuteButton.setText(_translate("MainWindow", "Mute"))
        self.labelzero.setText(_translate("MainWindow", "0"))
        self.labelone.setText(_translate("MainWindow", "1"))
        self.labeltwo.setText(_translate("MainWindow", "2"))
        self.labelthree.setText(_translate("MainWindow", "3"))
        self.labelfour.setText(_translate("MainWindow", "4"))
        self.labelfive.setText(_translate("MainWindow", "5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
